spring:
  banner:
    location: classpath:META-INF/banner.txt
  application:
    name: Verbarium
  datasource:
    url: jdbc:postgresql://localhost:5432/verbarium
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/verbarium
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration
    schemas: public

server:
  port: 8090

logging:
  file:
    name: verbarium.log
    path: /logs

# Social login properties
