spring:
  application:
    name: Verbarium
  datasource:
    url: jdbc:postgresql://localhost:5432/verbarium
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8090

# Start app (banner)
banner:
  location: classpath:META-INF/banner.txt

logging:
  file:
    name: verbarium.log
    path: /logs

# Social login properties
